

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




spring:
  application:
    name: school
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/schools
    username: verygood
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8070


application:
  config:
    student-url: http://localhost:8090/api/v1/students
