
spring:
  application:
    name: schools

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/schools
    username: verygood
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888


application:
  config:
    student-url: http://localhost:8222/api/v1/students

server:
  port: 8070